### PR TITLE
wrapped up install docs for simulation

### PR DESCRIPTION
**Pull request by sdhuerta**

### CODE REVIEW

**Comment by pyeatt** [comment]
I have ROS installed, and just finished installing mavros.  Can
you show me how to go from there?


On 12/02/2015 09:15 PM, sdhuerta wrote:
________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/SDSMT-CSC464-F15/landingpad/pull/2

Commit Summary

  *   added instructions and files for Pix ROS SITL
  *   added gcs install document

File Changes

  *   A Documents/Prototypes/Sprint_3/gcsinstall.pdf<https://github.com/SDSMT-CSC464-F15/landingpad/pull/2/files#diff-0> (0)
  *   A Documents/Prototypes/Sprint_3/gcsinstall.tex<https://github.com/SDSMT-CSC464-F15/landingpad/pull/2/files#diff-1> (58)
  *   A Documents/Prototypes/Sprint_3/install-ros.bash<https://github.com/SDSMT-CSC464-F15/landingpad/pull/2/files#diff-2> (47)
  *   A Documents/Prototypes/Sprint_3/mission.png<https://github.com/SDSMT-CSC464-F15/landingpad/pull/2/files#diff-3> (0)
  *   A Documents/Prototypes/Sprint_3/qgroundcontrol.png<https://github.com/SDSMT-CSC464-F15/landingpad/pull/2/files#diff-4> (0)
  *   A Documents/Prototypes/Sprint_3/rossitl.pdf<https://github.com/SDSMT-CSC464-F15/landingpad/pull/2/files#diff-5> (0)
  *   A Documents/Prototypes/Sprint_3/rossitl.png<https://github.com/SDSMT-CSC464-F15/landingpad/pull/2/files#diff-6> (0)
  *   A Documents/Prototypes/Sprint_3/rossitl.tex<https://github.com/SDSMT-CSC464-F15/landingpad/pull/2/files#diff-7> (79)
  *   A Documents/Prototypes/Sprint_3/rqt_graph.png<https://github.com/SDSMT-CSC464-F15/landingpad/pull/2/files#diff-8> (0)
  *   A Documents/Prototypes/Sprint_3/selectmission.png<https://github.com/SDSMT-CSC464-F15/landingpad/pull/2/files#diff-9> (0)
  *   A Documents/Prototypes/Sprint_3/setup-workspace.bash<https://github.com/SDSMT-CSC464-F15/landingpad/pull/2/files#diff-10> (49)

Patch Links:

  *   https://github.com/SDSMT-CSC464-F15/landingpad/pull/2.patch
  *   https://github.com/SDSMT-CSC464-F15/landingpad/pull/2.diff

-
Reply to this email directly or view it on GitHub<https://github.com/SDSMT-CSC464-F15/landingpad/pull/2>.


--
Larry D. Pyeatt, PhD.
Department of Mathematics and Computer Science
South Dakota School of Mines and Technology
larry.pyeatt@sdsmt.edu<mailto:larry.pyeatt@sdsmt.edu>
http://www.mcs.sdsmt.edu/lpyeatt

**Comment by sdhuerta** [comment]
Next, you will need to address the dependencies. The setup-workspace.bash file will clone the dependencies into the workspace. Though the bash file will use the current directory to setup the clones. 

From the beginning of the setup file: 
##############################################
WDIR=`pwd`
WORKSPACE=$WDIR/catkin_ws
 
# Setup workspace
mkdir -p $WORKSPACE/src
cd $WORKSPACE/src
catkin_init_workspace
cd $WORKSPACE
catkin_make
sh -c "echo 'source $WORKSPACE/devel/setup.bash' >> ~/.bashrc"

##############################################

It will then clone the appropriate repos. Finally it will catkin_make the space. If you decide to use the setup bash file as a handrail, please use the following:

$ catkin_make --cmake-args -DCONFIG=ros_sitl_simple

Creating this with just catkin_make will result in a number of errors.

Hope this helps!

**Comment by pyeatt** [comment]
Thanks.  Looks like the build worked just fine.  Now, where to from here?

Larry D. Pyeatt, PhD.
Department of Mathematics and Computer Science
South Dakota School of Mines and Technology
larry.pyeatt@sdsmt.edu<mailto:larry.pyeatt@sdsmt.edu>
http://www.mcs.sdsmt.edu/lpyeatt


On 12/03/2015 10:37 AM, sdhuerta wrote:

Next, you will need to address the dependencies. The setup-workspace.bash file will clone the dependencies into the workspace. Though the bash file will use the current directory to setup the clones.

From the beginning of the setup file:
##############################################
WDIR=pwd
WORKSPACE=$WDIR/catkin_ws

Setup workspace

mkdir -p $WORKSPACE/src
cd $WORKSPACE/src
catkin_init_workspace
cd $WORKSPACE
catkin_make
sh -c "echo 'source $WORKSPACE/devel/setup.bash' >> ~/.bashrc"

##############################################

It will then clone the appropriate repos. Finally it will catkin_make the space. If you decide to use the setup bash file as a handrail, please use the following:

$ catkin_make --cmake-args -DCONFIG=ros_sitl_simple

Creating this with just catkin_make will result in a number of errors.

Hope this helps!

-

**Comment by sdhuerta** [comment]
This is currently where the simulation team is stuck. The next step would be to start up the GCS and send commands via the GUI to our simulated UAV.  Using two separate terminals, you can run:

roslaunch px4 gazebo_iris_empty_world.launch

and in a separate terminal run:

rosrun px4 mavros_sitl.launch

I can receive pose information for the simulation through mavros_sitl, but I cannot send controls to arm or otherwise control the simulated UAV.

This is on the list of work item for Sprint 3.5:

Conversations related to integration of GCS and ROS SITL simulation:
https://groups.google.com/forum/#!topic/px4users/xLE40jdJMuU

https://github.com/mavlink/qgroundcontrol/issues/2242

**Comment by pyeatt** [comment]
Got it.  Thanks for bringing me up to date.

Larry D. Pyeatt, PhD.
Department of Mathematics and Computer Science
South Dakota School of Mines and Technology
larry.pyeatt@sdsmt.edu<mailto:larry.pyeatt@sdsmt.edu>
http://www.mcs.sdsmt.edu/lpyeatt


On 12/04/2015 11:28 AM, sdhuerta wrote:

This is currently where the simulation team is stuck. The next step would be to start up the GCS and send commands via the GUI to our simulated UAV. Using two separate terminals, you can run:

roslaunch px4 gazebo_iris_empty_world.launch

and in a separate terminal run:

rosrun px4 mavros_sitl.launch

I can receive pose information for the simulation through mavros_sitl, but I cannot send controls to arm or otherwise control the simulated UAV.

This is on the list of work item for Sprint 3.5:

Conversations related to integration of GCS and ROS SITL simulation:
https://groups.google.com/forum/#!topic/px4users/xLE40jdJMuU<https://groups.google.com/forum/#%21topic/px4users/xLE40jdJMuU>

mavlink/qgroundcontrol#2242<https://github.com/mavlink/qgroundcontrol/issues/2242>

-

**Pull request merged**
