### PR TITLE
Updating presentation

### PR DESCRIPTION
**Pull request by sdhuerta**

### CODE REVIEW

**Comment by drgeyer** [comment]
Looks great.

**Comment by sdhuerta** [comment]
having some issues with merge from documentation branch

**Comment by drgeyer** [comment]
Yea I see that, I'll let you get it all sorted out before I keep working.

**Comment by sdhuerta** [comment]
cool. I'm going to delete the pres2 in master along with the pdf. I took your changes and threw them into the document on my end.

**Comment by drgeyer** [comment]
Alright awesome.

**Comment by sdhuerta** [comment]
I'm out. I apologize about that mess. Hope I did not set you back to far.

**Comment by drgeyer** [comment]
My sections have been filled in, check them out and let me know if they are
terrible.

**Pull request merged**
